account: LU1832
client_id: 0
host: 127.0.0.1
# TWS
port: 7497
# IB Gateway
# port: 4002
strategy:
  DoubleMovingAverageCrossStrategy:
    active: false
    capital: 10000
    params:
      n_fast_ma: 20
      n_slow_ma: 200
    symbols:
    - NGX0 FUT NYMEX
  DualThrustStrategy:
    active: false
    capital: 10000
    params:
      G: 20
    symbols:
    - MESZ0 FUT GLOBEX
  MovingAverageCrossStrategy:
    active: false
    capital: 10000
    params:
      G: 20
    symbols:
    - CLX0 FUT NYMEX
  ActiveBuySellStrengthStrategy:
    active: false
    capital: 10000
    params:
      strength_abs_threshold: 200
    symbols:
      - NQZ0 FUT GLOBEX
  OrderPerIntervalStrategy:
    active: false
    capital: 50000
    order_end_time: 57000
    order_start_time: 09:40:00
    params:
      tick_trigger_threshold: 6000
    single_trade_limit: 3
    symbols:
    - ESZ0 FUT GLOBEX
    total_active_limit: 2
    total_cancel_limit: 5
    total_loss_limit: 500
    total_trade_limit: 15
theme: dark
total_active_limit: 3
total_cancel_limit: 10
total_loss_limit: 5000
total_trade_limit: 20
